services:
  webserver:
    build: ./docker/webserver
    image: ctcserve
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
      - ./ctcdb:/opt/ctcdb
      - ./letsencrypt/etc:/etc/letsencrypt
      - ./letsencrypt/log:/var/log/letsencrypt
      - /home/postcat:/var/mail
    links:
      - db

  db:
    image: mysql:5.7
    #https://github.com/docker-library/mysql/issues/149
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION"  --max_allowed_packet=100M
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=ctc
      - TZ=Pacific/Auckland

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
    volumes:
     - /sessions
    links:
     - db

       #webserver-dev:
       #  build: ./docker/webserver-dev
       #  image: ctcserve-dev
       #  ports:
       #    - "3000:443"
       #    - "3080:80"
       #  volumes:
       #    - ./www_dev:/var/www/html
       #    - ./ctcdb:/opt/ctcdb
       #    - ./letsencrypt_dev/etc:/etc/letsencrypt
       #    - ./letsencrypt_dev/log:/var/log/letsencrypt
       #  links:
       #    - db
