version: '2'

services:
  webserver:
    build: ./docker/webserver
    image: ctcserve
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
      # PENDING: May be better to add these using COPY in the dockerfile
      # https://github.com/docker-library/docs/tree/master/php
      - ./conf/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
      - ./conf/php.ini:/usr/local/etc/php/php.ini
    links:
      - db

  db:
    image: mysql:5.7
    #https://github.com/docker-library/mysql/issues/149
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION"  --max_allowed_packet=100M
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=ctc

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
    volumes:
     - /sessions
    links:
     - db
