CREATE USER IF NOT EXISTS 'ctcview'@'localhost' IDENTIFIED WITH mysql_native_password AS 'VerySecurePassword';GRANT SELECT ON *.* TO 'ctcview'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS joom35;
CREATE DATABASE IF NOT EXISTS ctc;
CREATE DATABASE IF NOT EXISTS newsletter;
CREATE DATABASE IF NOT EXISTS tripreports;
CREATE DATABASE IF NOT EXISTS trip;
